In [79]:
import sys
import os

from pathlib import Path
from timeit import time

build = Path(os.getcwd()).parent / "build"
print("Buscando librerias en", build)

Buscando librerias en /home/adrian/prueba/amd_ml/build


In [80]:
sys.path.append(str(build))

from amd_ml_py import linear_regression, SGD_linear_regression

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [81]:
def create_matrix(n_points: int, n_dimentions: int) -> list[np.ndarray]:
    #We generate a linear regression with coefficients 1, 2, 3, ...
    #We count with the bias term

    terms = np.zeros(n_dimentions + 1, dtype=np.float32)
    terms[0] = 1

    for i in range(n_dimentions):
        terms[i+1] = i+2

    X = np.ones((n_points, 1), dtype = np.float32)

    for i in range(n_dimentions):
        X = np.hstack((
            X, 
            np.linspace(0, 1, n_points).reshape(-1, 1) + np.random.randn(n_points).reshape(-1, 1)
            ))
    
    y = np.matmul(X, terms.reshape(-1, 1))

    return [X, y, terms]

In [82]:
def comparation(X: np.ndarray, y: np.ndarray, terms: np.ndarray, print_data = True) -> list[float]:
    a = time.time()
    parameters_sk = LinearRegression(fit_intercept=False).fit(X, y)
    b = time.time()

    c = time.time()
    params: np.ndarray = linear_regression(
        X, y,
        n_iter=1000,
        tolerance=0.01,
        learning_rate=0.1
    )
    d = time.time()

    time_amd = d-c
    time_sk = b-a

    if print_data:
        print(f"Parámetros encontrados: {params.round(1)}, tiempo usado: {time_amd} milisegundos")
        print(f"Parámetros encontrados sklearn: {parameters_sk.coef_.round(1)}, tiempo usado: {time_sk} milisegundos")
        print(f"Esperado: {terms}")

    return [time_amd, time_sk] 

In [83]:
X, y, terms = create_matrix(100, 2)
X

array([[ 1.        ,  0.49197828,  0.3262962 ],
       [ 1.        , -2.00686203, -0.05959525],
       [ 1.        ,  0.45768838,  0.1168911 ],
       [ 1.        ,  0.54891736,  0.95542314],
       [ 1.        ,  1.14226301,  0.69999404],
       [ 1.        ,  0.46695614,  0.19408352],
       [ 1.        , -1.41222003,  0.55102149],
       [ 1.        ,  1.38269984,  1.94097083],
       [ 1.        , -0.17996322,  0.58222053],
       [ 1.        ,  1.14903943, -0.61644027],
       [ 1.        , -0.6303727 , -0.33095964],
       [ 1.        ,  1.06443037,  0.4205597 ],
       [ 1.        , -1.18939906,  0.37616038],
       [ 1.        ,  0.57433281,  0.2516295 ],
       [ 1.        ,  1.55074204, -0.69559635],
       [ 1.        , -0.75344289, -0.52457539],
       [ 1.        , -0.33548521,  1.03812793],
       [ 1.        , -1.66248926, -1.8351113 ],
       [ 1.        ,  2.02550077,  0.97766441],
       [ 1.        , -0.33355935, -0.15868237],
       [ 1.        , -0.92964702,  0.242

In [84]:
y

array([[ 2.96284516],
       [-3.19250981],
       [ 2.26605006],
       [ 4.96410415],
       [ 5.38450815],
       [ 2.51616284],
       [-0.17137559],
       [ 9.58831216],
       [ 2.38673515],
       [ 1.44875804],
       [-1.25362431],
       [ 4.39053984],
       [-0.25031699],
       [ 2.90355411],
       [ 2.01469505],
       [-2.08061196],
       [ 3.44341339],
       [-7.83031243],
       [ 7.98399475],
       [-0.14316581],
       [-0.1306273 ],
       [ 1.43000768],
       [-4.01310383],
       [ 5.28836902],
       [ 2.44710355],
       [ 0.27096141],
       [ 5.98160378],
       [-0.98866794],
       [-0.80989284],
       [ 4.21810769],
       [ 1.25965815],
       [ 2.95672131],
       [ 2.13742815],
       [ 1.79751729],
       [ 0.31178042],
       [ 3.40714724],
       [ 8.03908187],
       [-2.69261314],
       [-1.51519434],
       [-0.24930511],
       [ 5.37677694],
       [ 0.79464766],
       [-2.16225794],
       [ 1.86209879],
       [ 3.10318055],
       [ 4

In [85]:
params: np.ndarray = linear_regression(
    X, y.ravel()
)

params

array([1., 1., 1.], dtype=float32)

Se ha alcanzado la tolerancia esperada a las 10 iteraciones

